version: "3.9"

services:
  db:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: 13152c0e-ce51-4e03-bebd-8e2c4fb359bf
      MARIADB_DATABASE: bexs_payments
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ms_network
    hostname: db.ms.local
    ports:
      - 13306:3306
    healthcheck:
      test: mysqladmin -p13152c0e-ce51-4e03-bebd-8e2c4fb359bf ping -h localhost
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 20
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db.ms.local
      PMA_USER: root
      PMA_PASSWORD: 13152c0e-ce51-4e03-bebd-8e2c4fb359bf
    networks:
      - ms_network
    hostname: phpmyadmin.ms.local
    ports:
      - 13307:80
    healthcheck:
      test: ["CMD", "curl", "--connect-timeout", "1", "-s", "http://127.0.0.1"]
      interval: 3s
      timeout: 1s
      retries: 20

volumes:
  db_data:

networks:
  ms_network:
    driver: bridge
