version: "3.9"

services:
  payments:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 9007
      DATABASE_HOST: db.ms.local
      DATABASE_PORT: 3306
      DATABASE_NAME: bexs_payments
      DATABASE_USER: root
      DATABASE_PASSWORD: 13152c0e-ce51-4e03-bebd-8e2c4fb359bf
      PAYMENT_DUPLICATED_SECONDS: 60
      RATE_USD: 4.75
      RATE_EUR: 5.50
      RATE_GBP: 6.35
    networks:
      ms_network:
        aliases:
          - transaction.ms.local
    hostname: transaction.ms.local
    ports:
      - 9007:9007
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "9007"]
      interval: 3s
      timeout: 1s
      retries: 20
  db:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: 13152c0e-ce51-4e03-bebd-8e2c4fb359bf
      MARIADB_DATABASE: bexs_payments
    volumes:
      - db_data:/var/lib/mysql
    networks:
      ms_network:
        aliases:
          - db.ms.local
    hostname: db.ms.local
    ports:
      - 13306:3306
    healthcheck:
      test: mysqladmin -p13152c0e-ce51-4e03-bebd-8e2c4fb359bf ping -h localhost
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 20
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db.ms.local
      PMA_USER: root
      PMA_PASSWORD: 13152c0e-ce51-4e03-bebd-8e2c4fb359bf
    networks:
      ms_network:
        aliases:
          - phpmyadmin.ms.local
    hostname: phpmyadmin.ms.local
    ports:
      - 13307:80
    healthcheck:
      test: ["CMD", "curl", "--connect-timeout", "1", "-s", "http://127.0.0.1"]
      interval: 3s
      timeout: 1s
      retries: 20

volumes:
  db_data:

networks:
  ms_network:
    driver: bridge
